# Generated by Django 5.0.7 on 2024-07-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=200)),
                ('year', models.DateTimeField()),
                ('genre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=200)),
                ('acclaimed', models.BooleanField()),
                ('image', models.ImageField(upload_to='')),
                ('movie_creation_date', models.DateTimeField(auto_now_add=True)),
                ('movie_modification_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
