# Generated by Django 5.0.7 on 2024-07-15 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_movie_acclaimed_alter_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_creation_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_modification_date',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
