# Generated by Django 5.0.7 on 2024-07-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_movie_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'película', 'verbose_name_plural': 'películas'},
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='acclaimed',
            field=models.BooleanField(null=True, verbose_name='Aclamada'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
