# Generated by Django 5.0.7 on 2024-07-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_alter_movie_options_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='writer',
            field=models.CharField(max_length=255, null=True, verbose_name='Escritor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=255, null=True, verbose_name='Director'),
        ),
    ]
