# Generated by Django 5.0.7 on 2024-07-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_movie_writer_alter_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.DateTimeField(null=True, verbose_name='Año'),
        ),
    ]
