# Generated by Django 5.0.7 on 2024-07-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
