# Generated by Django 5.0.7 on 2024-07-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=255, null=True, verbose_name='Diración'),
        ),
    ]
