# Generated by Django 5.0.7 on 2024-07-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_alter_movie_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
