# Generated by Django 5.0.7 on 2024-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0016_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
    ]
