# Generated by Django 5.0.7 on 2024-07-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.TextField(null=True, verbose_name='Video'),
        ),
    ]
